@startuml enviroment
skinparam node {
	backgroundColor<<workspace root>> mistyrose
}
skinparam frame {
  backgroundColor<<msys>> lightgreen
  backgroundColor<<MinGW>> lightcyan
}
skinparam component {
  borderColor black
}
node "Project" <<workspace root>> {
  folder ".vscode" {
    frame "launch.json" {
      [run]
      note left of [run]
        =Debug
        =[F5]
      end note
    }
    frame "tasks.json" {
      [build]
      note right of [build]
        =Build
        =[Ctrl]+[Shift]+[B]
      end note
    }
  }
  frame "Makefile" {
    [all:]
    [dump:]
    [clean:]
    [version:]
  }
  frame "version.sh" {
    [--version]
  }
}
frame "make.exe" <<msys>> {
  [make]
}
frame "gcc.exe" <<MinGW>> {
  [compile]
}
frame "objdump.exe" <<MinGW>> {
  [discompile]
}
frame "gdb.exe" <<MinGW>> {
  [debug]
}
frame "rm.exe" <<msys>> {
  [delete]
}
node "Output" <<workspace root>> {
  frame "program.exe" {
    [binary] <<->> [debug info] #black
  }
  folder "reverse" {
    frame "program.dasm" {
      [disassembler]
    }
  }
}

[build] .. Makefile #mistyrose
[build] ->> [make] #black
  [make] -->> Makefile #black
    [all:] -->> [compile] #black
      [compile] --> program.exe #blue
    [dump:] -->> [discompile] #black
      [discompile] -->> [binary] #black
      [discompile] --> reverse #blue
    [clean:] -->> [delete] #black
      [delete] --> Output #red
    [version:] -->> [--version] #black
      [--version] -->> gcc.exe #gray
      [--version] -->> objdump.exe #gray
      [--version] -->> rm.exe #gray
      [--version] ->> gdb.exe #gray
[run] -->> [debug] #black
  [debug] -->> [debug info] #black
@enduml